# Generated by Django 4.0.5 on 2022-06-18 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcean', '0002_parcean_user'),
        ('questions', '0002_question_created_at_question_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='given_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcean.parcean'),
        ),
    ]
