# Generated by Django 4.0.5 on 2022-06-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_item_imageurl_alter_item_image'),
        ('parcean', '0002_parcean_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcean',
            name='items',
            field=models.ManyToManyField(blank=True, to='shops.item'),
        ),
        migrations.AddField(
            model_name='parcean',
            name='wallet',
            field=models.IntegerField(default=0),
        ),
    ]
