# Generated by Django 4.0.5 on 2022-06-20 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parcean', '0003_parcean_items_parcean_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcean',
            name='items',
        ),
    ]
