# Generated by Django 4.0.5 on 2022-06-20 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parcean', '0004_remove_parcean_items'),
        ('shops', '0002_item_imageurl_alter_item_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('total', models.FloatField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shops.item')),
                ('parcean', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parcean.parcean')),
            ],
        ),
    ]
